### ISSUE TITLE
Bug - I can’t find TTS GOOGLE COMPONENT

### ISSUE THREAD

**Issue by riddik14** [jumping2000/notifier#67]
### Home Assistant Core Version

2024.01.02

### Home Assistant Installation Type

Home Assistant Operating System

### Description

 I can’t find TTS GOOGLE COMPONENT
 
Questo errore è restituito dalla card. Alexa funziona ma i dispositivi Google no. Con altri servizi di notifica che usano direttamente il servizio tts funziona, quindi tts funziona ed è presente. Controllato il nome aggiunto alla blueprint ed è lo stesso. 

Notifier_Dispatch: ------------------------------------------------------------
2024-01-07 11:53:39.793095 WARNING Notifier_Dispatch: Unexpected error in worker for App Notifier_Dispatch:
2024-01-07 11:53:39.793314 WARNING Notifier_Dispatch: Worker Ags: {'id': '9db57c54434a4479b61cf0aed3b7ad7b', 'name': 'Notifier_Dispatch', 'objectid': 'dc96ae2cf90243cc85bb17d755e11428', 'type': 'scheduler', 'function': <bound method Notifier_Dispatch.package_download of <notifier_dispatch.Notifier_Dispatch object at 0x7f998ae83490>>, 'pin_app': True, 'pin_thread': 2, 'kwargs': {'__thread_id': 'thread-2'}}
2024-01-07 11:53:39.793548 WARNING Notifier_Dispatch: ------------------------------------------------------------
2024-01-07 11:53:39.794576 WARNING Notifier_Dispatch: Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/appdaemon/threading.py", line 1022, in worker
    funcref(self.AD.sched.sanitize_timer_kwargs(app, args["kwargs"]))
  File "/homeassistant/appdaemon_apps/apps/notifier/notifier_dispatch.py", line 273, in package_download
    version_installed = self.get_local_version(cn_path, FILE_MAIN)  # <-- recupero versione locale
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/homeassistant/appdaemon_apps/apps/notifier/notifier_dispatch.py", line 198, in get_local_version
    if os.path.isfile(cn_path + file_names):
                      ~~~~~~~~^~~~~~~~~~~~
TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'

2024-01-07 11:53:39.794755 WARNING Notifier_Dispatch: ------------------------------------------------------------


### Automation YAML config

```

alias: Centro Notifiche - Configurazione Avvio
description: new
use_blueprint:
  path: caiosweet/notifier_startup_configuration.yaml
  input:
    person:
      - person.papaa
      - person.mamma
    alexa_media_player:
      - media_player.echo
      - media_player.firetvstick_di_domenico
      - media_player.nexxt
    alexa_group_player:
      - group.ovunque
    google_media_player:
      - media_player.camera_da_letto
      - media_player.cucina
      - media_player.giorno
      - media_player.cameretta
      - media_player.notte
      - media_player.soggiorno
      - media_player.tutti
    google_group_player:
      - group.google_home_all
    ha_event_notify:
      - notify.mobile_app_iphone_mimmo
    download: true
    personal_assistant: jarvis
```


### To Reproduce

Scrivi messaggio da interfono

invia 

errore visualizzato in alto. Google non parla
Alexa parla


### Expected behavior

—-

### Actual Behaviour

—-

### Additional Details

- [ ] I'd like to help developing a fix for this issue.

### Screenshots

_No response_

### Additional context

_No response_
