### ISSUE TITLE
Bug - Unable to use Google tts service 

### ISSUE THREAD

**Issue by jokerigno** [jumping2000/notifier#68]
### Home Assistant Core Version

2023.02.0

### Home Assistant Installation Type

Home Assistant Operating System

### Description

I'm unable to use google tts service (reverso works as expected).

I found the following message in appdaemon log:

> 2024-03-06 12:39:58.735921 ERROR GH_Manager: An error occurred in GH Manager - Errore nel Worker: Unknown service (default/tts/google_translate_say) in call_service from GH_Manager
> 2024-03-06 12:39:58.744600 INFO GH_Manager: (<class 'appdaemon.exceptions.ServiceException'>, ServiceException('Unknown service (default/tts/google_translate_say) in call_service from GH_Manager'), <traceback object at 0x7f71c6eb8100>)

Please notice that I renamed the tts service to google_translate_say (originally was google_it_it).

### Automation YAML config

```yaml
this is my gh_manager.yaml (updated in january 24)
___________

GH_Manager:
  module: gh_manager
  class: GH_Manager
  
  #log_level: DEBUG

  gh_service: tts.google
  ytube_player: media_player.ytube_music_player
  
  # Main hub
  gh_wait_time: input_number.notifier_tts_wait_time
  gh_select_media_player: select.notifier_player_google
  gh_sensor_media_player: sensor.notifier_player_google
  tts_period_of_day_volume: sensor.notifier_day_period_volume
  tts_language: input_select.notifier_language
  
  # Debug Sensor
  debug_sensor: sensor.notifier_debug_error
_________
```

### To Reproduce

set notifier to send tts message using script_mynotify and click on sent: message is received on telegram for example but not streamed via google minis

### Expected behavior

able to hear the tts message

### Actual Behaviour

when using google (no issue with reverso) the message is not streamed and I see an error info on appdaemon log

### Additional Details

- [X] I'd like to help developing a fix for this issue.

**Comment by riddik14** [comment]
gh_service: tts.google 
va aggiornato a
gh_service: google_translate.tts



Se risolvi chiudi il problema

**Comment by jokerigno** [comment]
Ciao,

credo che mi sfugga qualcosa. Nell'ultima versione dello zio (questa : https://github.com/jumping2000/notifier/releases/tag/2024.1.0) vedo ancora:

 gh_service: tts.google

se invece lo guardo da qui: https://github.com/jumping2000/notifier/blob/master/apps/notifier/gh_manager.yaml

manca proprio la voce gh_service.

**Comment by jokerigno** [comment]
Guardando la documentazione vedo che il tts di google chiama il servizio **tts.speak** e poi target **google.translate_say** (il service: tts.google_translate_say è "[legacy](https://www.home-assistant.io/integrations/tts#service-say-legacy)")

_________________

```
service: tts.speak
target:
  entity_id: tts.google_translate_say
data:
  cache: true
  media_player_entity_id: media_player.cucina
  message: prova
```

__________

che forse vada cambiato [questo ](https://github.com/jumping2000/notifier/blob/master/apps/notifier/notifier_dispatch.py#L19)DEFAULT_TTS_GOOGLE = "google_translate_say" nel notifier_dispatch? Chiedo perchè qui quell o reverso è invariato (e infatti funziona)
